import React from 'react';

const Blogs = () => {
    return (
        <div>
            <h1 className='text-center text-2xl m-4'>This is my blog page</h1>
            <div className='p-8'>
                <li className='font-bold'>Lorem, ipsum dolor sit amet consectetur adipisicing.</li>
                <div className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam  inventore incidunt dolor exercitationem delectus ab eligendi tempore. Odit quo et reprehenderit, a accusamus veniam corrupti! Mollitia optio, recusandae magnam quod soluta obcaecati distinctio officiis totam excepturi animi minus, magni similique iusto atque rem explicabo nostrum ipsum? A accusamus doloribus id fuga, ratione vero tempore magnam accusantium eaque, nemo, impedit nostrum aspernatur iusto nulla voluptate in! Rerum rem, sit alias dignissimos laboriosam provident quod doloribus aliquam at sunt quam, aperiam id nemo mollitia ea ab praesentium, odit fugit. Odit, aliquam accusantium voluptatum illum nesciunt hic maxime. Id, soluta. Veniam voluptate ratione hic voluptatem eligendi sed similique est impedit quasi deserunt optio assumenda eius ex, ab unde fugit itaque maxime labore sapiente? Veniam ea, non dolore suscipit dicta neque laboriosam dolorem itaque est iusto tempora veritatis illum! Possimus, itaque sequi corporis assumenda deserunt delectus facere aliquam, molestiae animi aspernatur alias perferendis ex illum modi blanditiis quasi facilis vitae odio aut molestias excepturi ad ipsa sit quidem! Quo inventore, a quasi tempore consectetur architecto harum fuga magnam?</div>
            </div>
            <div className='p-8'>
                <li className='font-bold'>Lorem, ipsum dolor sit amet consectetur adipisicing.</li>
                <div className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam soluta, ullam quam quia officiis nobis, illo temporibus aut quidem laborum numquam facilis, modi labore dicta accusamus neque. Et laudantium minima obcaecati itaque reiciendis vel facilis velit deleniti accusamus? Fugiat, ipsam. Repudiandae asperiores et, dolor ipsam hic, similique recusandae ducimus necessitatibus voluptatibus maiores eos ex, placeat voluptatem labore itaque aliquid dicta quibusdam corrupti doloribus nobis? Quos sint iure eaque tempora magnam in, voluptas rerum hic illum enim fugiat deserunt exercitationem nisi. Nostrum, excepturi! Doloribus magni error maxime, rerum ut similique totam inventore debitis? Ipsa, ad voluptatibus natus non aspernatur mollitia. Impedit voluptatem consequatur, velit, ipsam itaque voluptas laborum mollitia provident sunt assumenda architecto. Quia quod nemo alias minima consequatur earum architecto magnam autem. Ad magni explicabo commodi quas quo at voluptate provident vel! Dignissimos voluptate labore inventore incidunt dolor exercitationem delectus ab eligendi tempore. Odit quo et reprehenderit, a accusamus veniam corrupti! Mollitia optio, recusandae magnam quod soluta obcaecati distinctio officiis totam excepturi animi minus, magni similique iusto atque rem explicabo nostrum ipsum? A accusamus iusto nulla voluptate in! Rerum rem, sit alias dignissimos laboriosam provident quod doloribus aliquam at sunt quam, aperiam id nemo mollitia ea ab praesentium, odit fugit. Odit, aliquam accusantium voluptatum illum nesciunt hic maxime. Id, soluta. Veniam voluptate ratione hic voluptatem eligendi sed similique est impedit quasi deserunt optio assumenda eius ex, ab unde fugit itaque maxime labore sapiente? Veniam ea, non dolore suscipit dicta neque laboriosam dolorem itaque est iusto tempora veritatis illum! Possimus, itaque sequi corporis assumenda deserunt delectus facere aliquam, molestiae animi aspernatur alias perferendis ex illum modi blanditiis quasi facilis vitae odio aut molestias excepturi ad ipsa sit quidem! Quo inventore, a quasi tempore consectetur architecto harum fuga magnam?</div>
            </div>
            <div className='p-8'>
                <li className='font-bold'>Lorem, ipsum dolor sit amet consectetur adipisicing.</li>
                <div className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam soluta, ullam quam quia officiis nobis, illo temporibus aut quidem laborum numquam facilis, modi labore dicta accusamus neque. Et laudantium minima obcaecati itaque reiciendis vel facilis velit deleniti accusamus? Fugiat, ipsam. Repudiandae asperiores et, dolor ipsam hic, similique recusandae ducimus necessitatibus voluptatibus maiores eos ex, placeat voluptatem labore itaque aliquid dicta quibusdam corrupti doloribus nobis? Quos sint iure eaque tempora magnam in, voluptas rerum architecto harum fuga magnam?</div>
            </div>
            <div className='p-8'>
                <li className='font-bold'>Lorem, ipsum dolor sit amet consectetur adipisicing.</li>
                <div className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam soluta, ullam quam quia officiis nobis, illo temporibus aut quidem laborum numquam facilis, modi labore dicta accusamus neque. Et laudantium minima obcaecati itaque reiciendis vel facilis velit deleniti accusamus? Fugiat, ipsam. Repudiandae asperiores et, dolor ipsam hic, similique recusandae ducimus necessitatibus voluptatibus maiores eos ex, placeat voluptatem labore itaque aliquid dicta quibusdam corrupti doloribus nobis? Quos sint iure eaque tempora magnam in, voluptas rerum hic illum enim fugiat deserunt exercitationem nisi. Nostrum, excepturi! Doloribus magni error maxime, rerum ut similique totam inventore debitis? Ipsa, ad voluptatibus natus non aspealiquam at sunt quam, aperiam id nemo mollitia ea ab praesentium, odit fugit. Odit, aliquam accusantium voluptatum illum nesciunt hic maxime. Id, soluta. Veniam voluptate ratione hic voluptatem eligendi sed similique est impedit quasi deserunt optio assumenda eius ex, ab unde fugit itaque maxime labore sapiente? Veniam ea, non dolore suscipit dicta neque laboriosam dolorem itaque est iusto tempora veritatis illum! Possimus, itaque sequi corporis assumenda deserunt delectus facere aliquam, molestiae animi aspernatur alias perferendis ex illum modi blanditiis quasi facilis vitae odio aut molestias excepturi ad ipsa sit quidem! Quo inventore, a quasi tempore consectetur architecto harum fuga magnam?</div>
            </div>
            <div className='p-8'>
                <li className='font-bold'>Lorem, ipsum dolor sit amet consectetur adipisicing.</li>
                <div className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam soluta, ullam quam quia officiis nobis, illo temporibus aut quidem laborum numquam facilis, modi labore dicta accusamus neque. Et laudantium minima obcaecati itaque reiciendis vel facilis velit deleniti accusamus? Fugiat, ipsam. Repudiandae asperiores et, dolor ipsam hic, similique recusandae ducimus necessitatibus voluptatibus maiores eos ex, placeat voluptatem labore itaque aliquid dicta quibusdam corrupti doloribus nobis? Quos sint iure eaque tempora magnam in, voluptas rerum hic illum enim fugiat deserunt exercitationem nisi. Nostrum, excepturi! Doloribus magni error maxime, rerum ut similique totam inventore debitis? Ipsa, ad voluptatibus natus non aspernatur mollitia. Impedit voluptatem consequatur, velit, ipsam itaque voluptas laborum mollitia provident sunt assumenda architecto. Quia quod nemo alias minima consequatur earum architecto magnam autem. Ad magni explicabo commodi quas quo at voluptate provident vel! Dignissimos voluptate labore inventore incidunt dolor exercitationem delectus ab eligendi tempore. Odit quo et reprehenderit, a accusamus veniam corrupti! Mollitia optio, recusandae magnam quod soluta obcaecati distinctio officiis totam excepturi animi minus, magni similique iusto atque rem explicabo nostrum ipsum? A accusamus voluptatem eligendi sed similique est impedit quasi deserunt optio assumenda eius ex, ab unde fugit itaque maxime labore sapiente? Veniam ea, non dolore suscipit dicta neque laboriosam dolorem itaque est iusto tempora veritatis illum! Possimus, itaque sequi corporis assumenda deserunt delectus facere aliquam, molestiae animi aspernatur alias perferendis ex illum modi blanditiis quasi facilis vitae odio aut molestias excepturi ad ipsa sit quidem! Quo inventore, a quasi tempore consectetur architecto harum fuga magnam?</div>
            </div>
        </div>
    );
};

export default Blogs;